cursor_shape beam
confirm_os_window_close 0

background_image ~/OneDrive/Pictures/background/misc/is3.jpg
background_image_layout cscaled
background_opacity 1
background_tint 0.9
inactive_text_alpha 0.5

linux_display_server x11

enabled_layouts splits

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

map ctrl+t launch --location=vsplit --cwd=current
map ctrl+d launch --location=hsplit --cwd=current
map ctrl+w close_window

map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
map ctrl+home resize_window reset  # reset to defaults

map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# jesus christ
map ctrl+1 first_window
map ctrl+2 second_window
map ctrl+3 third_window
map ctrl+4 fourth_window
map ctrl+5 fifth_window
map ctrl+6 sixth_window
map ctrl+7 seventh_window
map ctrl+8 eigth_window
map ctrl+9 ninth_window

map ctrl+tab next_window
map ctrl+shift+tab previous_window

map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+8 goto_tab 8
map ctrl+shift+9 goto_tab 9

# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME
